# Generated by Django 4.1.7 on 2023-04-12 15:54

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='avatar_ppoi',
            field=versatileimagefield.fields.PPOIField(default='0.5x0.5', editable=False, max_length=20),
        ),
        migrations.AlterField(
            model_name='school',
            name='logo',
            field=versatileimagefield.fields.VersatileImageField(upload_to='school', verbose_name='Avatar'),
        ),
    ]
