# Generated by Django 4.1.7 on 2023-04-12 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_myuser_optional_image_alter_myuser_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='optional_image',
        ),
    ]
