# Generated by Django 4.1.7 on 2023-04-24 23:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_myuser_uuid_alter_student_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='uuid',
            field=models.CharField(default=uuid.uuid4, max_length=100, unique=True),
        ),
    ]
